import { useQuery } from '@tanstack/react-query'
import { ArrowUpRight, BarChart3, Clock3, Database, Gauge, RefreshCw, Server, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../../api/client'
import { Button, Card, ErrorState, LoadingState, PageHeader, StatusPill } from '../../components/Ui'

function formatNumber(value?: string | number) { const number = Number(value || 0); return Number.isFinite(number) ? new Intl.NumberFormat('zh-CN').format(number) : '—' }
function Metric({ label, value, foot, icon: Icon }: { label: string; value: string; foot: string; icon: typeof UsersRound }) { return <Card className="metric-card"><div className="metric-label">{label}</div><div className="metric-value">{formatNumber(value)}</div><div className="metric-foot"><Icon size={13} /><span>{foot}</span></div></Card> }

export function Dashboard() {
  const query = useQuery({ queryKey: ['dashboard'], queryFn: api.dashboard, refetchInterval: 30_000 })
  if (query.isLoading) return <><PageHeader title="运行总览" description="正在读取本机游戏服的实时摘要" /><LoadingState /></>
  if (query.isError || !query.data) return <><PageHeader title="运行总览" /><ErrorState message={query.error instanceof Error ? query.error.message : undefined} onRetry={() => query.refetch()} /></>
  const data = query.data
  return <><PageHeader eyebrow="OPERATIONS / OVERVIEW" title="运行总览" description="今天的服务器状态与关键运营指标" action={<Button variant="secondary" onClick={() => query.refetch()}><RefreshCw size={15} />刷新数据</Button>} /><div className="grid grid-4"><Metric label="在线角色" value={data.online} foot="Redis 实时标记" icon={UsersRound} /><Metric label="角色总量" value={data.players} foot="已创建角色" icon={Gauge} /><Metric label="账号总量" value={data.accounts} foot="注册账号" icon={Database} /><Metric label="24 小时登录" value={data.recentLogins24h} foot="过去 24 小时" icon={Clock3} /></div><div className="grid grid-2" style={{ marginTop: 16 }}><Card className="chart-card"><div className="section-title"><h2>在线趋势</h2><span>LIVE / 近 24 小时</span></div><div className="card-pad"><svg className="sparkline" viewBox="0 0 720 130" preserveAspectRatio="none" role="img" aria-label="在线趋势占位图"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#22c55e" stopOpacity=".28" /><stop offset="1" stopColor="#22c55e" stopOpacity="0" /></linearGradient></defs><path d="M0 103 C35 91 52 97 84 89 S135 95 167 72 S216 87 252 66 S308 69 342 78 S388 47 427 59 S478 31 513 49 S565 58 594 36 S650 47 720 14 V130 H0 Z" fill="url(#fill)" /><path d="M0 103 C35 91 52 97 84 89 S135 95 167 72 S216 87 252 66 S308 69 342 78 S388 47 427 59 S478 31 513 49 S565 58 594 36 S650 47 720 14" fill="none" stroke="#4ade80" strokeWidth="2" /></svg><div className="metric-foot"><span className="positive">当前 {formatNumber(data.online)} 人在线</span><span>· 每 30 秒刷新</span></div></div></Card><Card><div className="section-title"><h2>依赖健康</h2><span>REV {data.configRevision || '—'}</span></div><div className="health-list">{([['mysql', 'MySQL 数据库', data.health.mysql], ['redis', 'Redis 控制通道', data.health.redis], ['game', '游戏 TCP 服务', data.health.game]] as const).map(([key, label, dependency]) => <div className="health-row" key={key}><div><Server size={15} /><div><b>{label}</b><small>{dependency.detail || '连接正常'}</small></div></div><div><span className="health-latency">{dependency.latencyMs} ms</span><StatusPill status={dependency.status}>{dependency.status === 'up' ? '正常' : '异常'}</StatusPill></div></div>)}</div></Card></div><Card style={{ marginTop: 16 }}><div className="section-title"><h2>快捷入口</h2><span>常用管理动作</span></div><div className="quick-actions"><Link to="/players"><UsersRound size={17} /><span>查找角色</span><ArrowUpRight size={14} /></Link><Link to="/configs"><Server size={17} /><span>配置中心</span><ArrowUpRight size={14} /></Link><Link to="/audit"><BarChart3 size={17} /><span>审计日志</span><ArrowUpRight size={14} /></Link></div></Card></>
}
