import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, FileCode2, History, RotateCcw, Save, Send, ShieldCheck, TestTube2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api } from '../../api/client'
import { Button, Card, EmptyState, ErrorState, Field, LoadingState, PageHeader, StatusPill } from '../../components/Ui'

function ConfigEditor({ name }: { name: string }) {
  const client = useQueryClient(); const config = useQuery({ queryKey: ['config', name], queryFn: () => api.config(name), enabled: !!name }); const revisions = useQuery({ queryKey: ['config-revisions', name], queryFn: () => api.revisions(name), enabled: !!name }); const [yaml, setYaml] = useState(''); const [note, setNote] = useState(''); const [message, setMessage] = useState<{ tone: 'success' | 'danger' | 'info'; text: string } | null>(null)
  useEffect(() => { if (config.data) setYaml(config.data.contentYaml) }, [config.data])
  const validate = useMutation({ mutationFn: () => api.validateConfig(name, yaml), onSuccess: () => setMessage({ tone: 'success', text: 'YAML 校验通过，可以创建草稿或发布。' }), onError: err => setMessage({ tone: 'danger', text: err instanceof Error ? err.message : '校验失败' }) })
  const draft = useMutation({ mutationFn: () => api.saveDraft(name, yaml, config.data?.revision || '0'), onSuccess: value => setMessage({ tone: 'success', text: `草稿 #${value.draftId} 已保存。` }), onError: err => setMessage({ tone: 'danger', text: err instanceof Error ? err.message : '保存失败' }) })
  const publish = useMutation({ mutationFn: () => api.publishConfig(name, yaml, note), onSuccess: value => { setMessage({ tone: 'success', text: `已发布 revision ${value.revision}，Redis 热重载通知已发送。` }); void client.invalidateQueries({ queryKey: ['config', name] }); void client.invalidateQueries({ queryKey: ['config-revisions', name] }) }, onError: err => setMessage({ tone: 'danger', text: err instanceof Error ? err.message : '发布失败' }) })
  const rollback = useMutation({ mutationFn: (revision: string) => api.rollbackConfig(name, revision, `GM 控制台回滚至 ${revision}`), onSuccess: value => { setMessage({ tone: 'success', text: `已生成回滚 revision ${value.revision}。` }); void client.invalidateQueries({ queryKey: ['config', name] }); void client.invalidateQueries({ queryKey: ['config-revisions', name] }) }, onError: err => setMessage({ tone: 'danger', text: err instanceof Error ? err.message : '回滚失败' }) })
  if (config.isLoading) return <LoadingState />; if (config.isError || !config.data) return <ErrorState message={config.error instanceof Error ? config.error.message : undefined} onRetry={() => config.refetch()} />
  return <Card><div className="editor-head"><div><h2><FileCode2 size={15} style={{ verticalAlign: 'middle', marginRight: 7 }} />{name}</h2><span className="muted" style={{ fontSize: 11 }}>当前 revision：{config.data.revision || '未发布'}</span></div><div className="editor-actions"><Button variant="secondary" loading={validate.isPending} onClick={() => validate.mutate()}><TestTube2 size={14} />校验</Button><Button variant="secondary" loading={draft.isPending} onClick={() => draft.mutate()}><Save size={14} />保存草稿</Button><Button loading={publish.isPending} onClick={() => publish.mutate()}><Send size={14} />发布</Button></div></div><div className="editor-body">{message ? <div className={`notice ${message.tone}`} style={{ marginBottom: 13 }}>{message.text}</div> : null}<Field label="YAML 内容" hint="仅允许白名单配置；发布前会执行服务端校验"><textarea className="textarea" style={{ minHeight: 390 }} spellCheck={false} value={yaml} onChange={e => setYaml(e.target.value)} /></Field><div style={{ marginTop: 14 }}><Field label="发布备注"><input className="input" value={note} onChange={e => setNote(e.target.value)} placeholder="例如：周末活动倍率调整" /></Field></div><div style={{ marginTop: 21 }}><div className="section-title" style={{ padding: '13px 0' }}><h2><History size={14} style={{ verticalAlign: 'middle', marginRight: 7 }} />历史 revision</h2><span>最近 100 个</span></div>{revisions.isLoading ? <LoadingState /> : revisions.data?.items.length ? <div className="revision-list">{revisions.data.items.map(revision => <div className="revision-row" key={revision.revision}><div><span className="mono">rev {revision.revision}</span><small> · {revision.publisher} · {revision.note || '无备注'}</small></div><Button variant="ghost" loading={rollback.isPending} onClick={() => { if (window.confirm(`确认回滚到 revision ${revision.revision}？这会生成新的 revision。`)) rollback.mutate(revision.revision) }}><RotateCcw size={13} />回滚</Button></div>)}</div> : <EmptyState message="暂无 GM 发布记录" />}</div></div></Card>
}

export function Configs() {
  const configs = useQuery({ queryKey: ['configs'], queryFn: api.configs }); const [selected, setSelected] = useState('')
  useEffect(() => { if (!selected && configs.data?.items[0]) setSelected(configs.data.items[0].name) }, [configs.data, selected])
  return <><PageHeader eyebrow="CONTROL PLANE / CONFIG" title="配置中心" description="编辑白名单 YAML，校验后发布并触发 Redis 热重载" /><div className="notice" style={{ marginBottom: 16 }}><ShieldCheck size={15} style={{ verticalAlign: 'middle', marginRight: 7 }} />配置发布是受控事务：不会执行任意 SQL，也不会读取 datatable_json 作为生产配置。</div>{configs.isLoading ? <LoadingState /> : configs.isError ? <ErrorState message={configs.error instanceof Error ? configs.error.message : undefined} onRetry={() => configs.refetch()} /> : <div className="config-layout"><Card className="config-list">{configs.data?.items.length ? configs.data.items.map(config => <button type="button" className={selected === config.name ? 'config-item active' : 'config-item'} key={config.name} onClick={() => setSelected(config.name)}><span>{config.name}</span><small>{config.nodes} nodes</small></button>) : <EmptyState message="暂无可编辑配置" />}</Card>{selected ? <ConfigEditor name={selected} /> : <Card><EmptyState message="从左侧选择一项配置" /></Card>}</div>}</>
}
