import { useQuery } from '@tanstack/react-query'
import { Crown, PackageSearch, Search, Swords } from 'lucide-react'
import { useState } from 'react'
import { api } from '../../api/client'
import { Card, EmptyState, ErrorState, LoadingState, PageHeader, StatusPill } from '../../components/Ui'

function val(item: Record<string, unknown>, ...keys: string[]) { const key = keys.find(k => item[k] !== undefined); return key ? String(item[key] ?? '—') : '—' }
function GenericTable({ items, kind }: { items: Record<string, unknown>[]; kind: string }) { if (!items.length) return <EmptyState message="暂无记录" />; const cols = Object.keys(items[0]).slice(0, kind === 'bosses' ? 8 : 7); return <div className="table-wrap"><table className="data-table"><thead><tr>{cols.map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{items.map((item, i) => <tr key={i}>{cols.map(c => <td className="mono" key={c}>{val(item, c)}</td>)}</tr>)}</tbody></table></div> }
export function Operations() {
  const [tab, setTab] = useState<'families' | 'consignments' | 'bosses'>('families'); const [query, setQuery] = useState('');
  const families = useQuery({ queryKey: ['families', query], queryFn: () => api.families({ query }), enabled: tab === 'families' }); const consignments = useQuery({ queryKey: ['consignments'], queryFn: () => api.consignments({}), enabled: tab === 'consignments' }); const bosses = useQuery({ queryKey: ['bosses'], queryFn: api.bosses, enabled: tab === 'bosses' });
  const current = tab === 'families' ? families : tab === 'consignments' ? consignments : bosses; const items = tab === 'bosses' ? [...(bosses.data?.world || []), ...(bosses.data?.family || [])] : (current.data && 'items' in current.data ? current.data.items : []) as Record<string, unknown>[]
  return <><PageHeader eyebrow="OPERATIONS / WORLD" title="运营数据" description="查看家族、寄售与 Boss 的只读运营快照" /><div className="tabs" style={{ marginBottom: 16 }}><button className={tab === 'families' ? 'tab active' : 'tab'} onClick={() => setTab('families')}><Crown size={14} />家族</button><button className={tab === 'consignments' ? 'tab active' : 'tab'} onClick={() => setTab('consignments')}><PackageSearch size={14} />寄售</button><button className={tab === 'bosses' ? 'tab active' : 'tab'} onClick={() => setTab('bosses')}><Swords size={14} />Boss</button></div>{tab === 'families' ? <div className="toolbar"><div className="search"><Search size={16} /><input className="input" value={query} onChange={e => setQuery(e.target.value)} placeholder="按家族名搜索" /></div></div> : null}<Card><div className="section-title"><h2>{tab === 'families' ? '家族列表' : tab === 'consignments' ? '寄售列表' : 'Boss 状态'}</h2><span>{current.isLoading ? '读取中' : `${items.length} 条记录`}</span></div>{current.isLoading ? <LoadingState /> : current.isError ? <ErrorState message={current.error instanceof Error ? current.error.message : undefined} onRetry={() => current.refetch()} /> : <GenericTable items={items} kind={tab} />}<div className="pagination"><span>只读快照 · 权限由服务端控制</span><StatusPill status="ok">只读</StatusPill></div></Card></>
}
